version: '3.7'
services:
  postgresdb:
    image: postgres:15.1
    container_name: postgresdb
    environment:
      POSTGRES_DB: necpptunedb
      POSTGRES_USER: ncpptAdmin
      POSTGRES_PASSWORD: myselfpreorderblinkedalmanacchubby
    ports:
      - "5432:5432"

  miniodb:
    image: quay.io/minio/minio:RELEASE.2023-01-31T02-24-19Z
    container_name: miniodb
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-volume:/data
    command: ["server", "/data", "--console-address", ":9001"]

volumes:
  minio-volume:
    name: minio-volume
    external: false