version: '3.7'
services:
  postgresdb:
    image: postgres:15.1
    container_name: postgresdb
    environment:
      POSTGRES_DB: necpptunedb
      POSTGRES_USER: ncpptAdmin
      POSTGRES_PASSWORD: myselfpreorderblinkedalmanacchubby
    ports:
      - "5432:5432"